# Default configuration applied to all displays
[default]
duration = "2s"
mode = "center"
sorting = "ascending"

# Configuration for any display not explicitly listed
[any]
path = "/home/alien/Documents/wofiW/go-to-school.jpg"

# Specific configuration for a display
[DP-3]
path = "/home/alien/Documents/Wallpaper"
